/*
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for ULTRASONIC driver.
 *
 * Author: Mohamed Khaled
 *
 */


/***********************************************************************
 *                      Include Module header file                      *
 ***********************************************************************/
#include "ultrasonic.h"



/***********************************************************************
 *              Include the other required header files                 *
 ***********************************************************************/
#include <avr/io.h> /* To use IO registers */
#include <util/delay.h>
#include "gpio.h"
#include "icu.h"


/***********************************************************************
 *                            Global Variables                          *
 ***********************************************************************/
/* Counts the number of captured edges by icu */
static uint8 g_icuTick = 0;
static uint16 g_echoHighTime = 0;


/***********************************************************************
 *                      Local Functions Prototypes                      *
 ***********************************************************************/
/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasnoic_edgeProcessing( void );
/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */
static void Ultrasonic_Trigger( void );



/***********************************************************************
 *                          Functions Definitions                       *
 ***********************************************************************/
/*
 * Description:
 * Initialize the ICU driver F_ICU = F_CPU/8 and rising edge at first.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init( void )
{
	/* Initializing ICU Module */
	Icu_ConfigType icuCofigurations = { F_CPU_8, RISING };
	Icu_init(&icuCofigurations);
	/* Set call back function of ICU */
	Icu_setCallBack(Ultrasnoic_edgeProcessing);
	/* Trigger pin as output, echo pin is set as input in ICU_init()*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);
}

/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment
 */
uint16 Ultrasonic_readDistance( void )
{
	/* Trigger ultrasonic and wait for high time to be calculated. */
	Ultrasonic_Trigger();
	while(g_echoHighTime == 0);
	/*
	 * F_CPU = 8,000,000 Hz
	 * F_ICU = 1,000,000 Hz
	 * So time in seconds = 0.000001 * High Time
	 */
	return g_echoHighTime / 58.8;
}


/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasnoic_edgeProcessing( void )
{
	g_icuTick++;
	switch(g_icuTick)
	{
	case 1:
		/* Save time of first rising edge and change icu to capture falling edge. */
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
		break;
	case 2:
		/* Get high time of Echo and stop icu. */
		g_echoHighTime = Icu_getInputCaptureValue();
		Icu_DeInit();
		g_icuTick = 0;
		break;
	}
}



/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */
static void Ultrasonic_Trigger( void )
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}
